export const CUSTOMER_TYPES = ['SCHOOL','B2C_CUSTOMER','CORPORATE','STUDENT_GROUP','OTHER'] as const;
export const CUSTOMER_STATUSES = ['ACTIVE','INACTIVE','LEAD','PROSPECT','REPEAT_CUSTOMER','BLACKLISTED'] as const;
export const CUSTOMER_TAGS = ['HIGH_VALUE','FAST_PAYER','SLOW_PAYER','PRICE_SENSITIVE','REQUIRES_FOLLOW_UP','FREQUENT_BUYER','STUDENT_GROUP','CORPORATE'] as const;
