'use client';
import Link from 'next/link';
import { useRouter } from 'next/navigation';
import { useState } from 'react';
import { CUSTOMER_STATUSES, CUSTOMER_TAGS, CUSTOMER_TYPES } from './constants';
import { PageHeader } from '@/components/ui/PageHeader';
import { StatusBadge } from '@/components/ui/StatusBadge';

export function CustomersClient({ customers }: { customers: any[] }) {
  const router = useRouter();
  const [open, setOpen] = useState(false); const [editing, setEditing] = useState<any>(null); const [msg, setMsg] = useState('');
  const [form, setForm] = useState<any>({ customerType:'SCHOOL', status:'LEAD', tags:[], billingSame:true });
  const save = async () => {
    const method = editing ? 'PATCH' : 'POST'; const url = editing ? `/api/customers/${editing.id}` : '/api/customers';
    const payload = { ...form, tags: form.tags ?? [], billingAddressLine1: form.billingSame ? form.deliveryAddressLine1 : form.billingAddressLine1, billingAddressLine2: form.billingSame ? form.deliveryAddressLine2 : form.billingAddressLine2, billingPostalCode: form.billingSame ? form.deliveryPostalCode : form.billingPostalCode, billingCountry: form.billingSame ? form.deliveryCountry : form.billingCountry };
    const res = await fetch(url,{method,headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)}); const data = await res.json(); if(!res.ok){setMsg(data.error);return;} setMsg(data.warning ?? 'Saved'); setOpen(false); router.refresh();
  };
  const archive = async(id:string)=>{await fetch(`/api/customers/${id}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({status:'INACTIVE'})});router.refresh();};
  const del = async(id:string)=>{const r=await fetch(`/api/customers/${id}`,{method:'DELETE'});const d=await r.json();if(!r.ok){setMsg(d.error);return;}router.refresh();};

  return <section className="space-y-4"><PageHeader title="Customers" description="Manage customer contacts, addresses, reminders, and account status." primaryActionLabel="Add Customer" />
    <div className="rounded-lg border bg-white p-3 flex gap-2"><input className="border rounded px-3 py-2 text-sm" placeholder="Search organisation, contact, phone" onKeyDown={(e)=>{if(e.key==='Enter'){router.push(`/customers?q=${encodeURIComponent((e.target as HTMLInputElement).value)}`)}}}/><select className="border rounded px-3 py-2 text-sm" onChange={(e)=>router.push(`/customers?type=${e.target.value}`)}><option value=''>All types</option>{CUSTOMER_TYPES.map(t=><option key={t}>{t}</option>)}</select><button className="border rounded px-3 py-2 text-sm" onClick={()=>setMsg('Excel export will be built later.')}>Excel Export</button><button className="ml-auto bg-slate-900 text-white rounded px-3 py-2 text-sm" onClick={()=>{setEditing(null);setForm({ customerType:'SCHOOL', status:'LEAD', tags:[], billingSame:true });setOpen(true);}}>Add Customer</button></div>
    {msg && <p className='text-sm text-amber-700'>{msg}</p>}
    <div className='overflow-x-auto rounded-lg border bg-white'><table className='w-full min-w-[1200px] text-sm'><thead className='bg-slate-50'><tr>{['Contact','Organisation','Email','Phone','Type','Status','Last order','Total revenue','Outstanding','Created','Actions'].map(h=><th key={h} className='px-3 py-2 text-left'>{h}</th>)}</tr></thead><tbody>{customers.map(c=><tr key={c.id} className='border-t'><td className='px-3 py-2'><Link href={`/customers/${c.id}`} className='font-medium hover:underline'>{c.contactName}</Link></td><td className='px-3 py-2'>{c.companyName || '-'}</td><td className='px-3 py-2'>{c.email}</td><td className='px-3 py-2'>{c.phone}</td><td className='px-3 py-2'>{c.customerType}</td><td className='px-3 py-2'><StatusBadge status={c.status.replace('_',' ')} /></td><td className='px-3 py-2'>-</td><td className='px-3 py-2'>SGD 0.00</td><td className='px-3 py-2'>SGD 0.00</td><td className='px-3 py-2'>{new Date(c.createdAt).toLocaleDateString()}</td><td className='px-3 py-2 space-x-2'><button onClick={()=>{setEditing(c);setForm(c);setOpen(true)}}>Edit</button><button onClick={()=>setMsg('Create quotation will be built in a later module.')}>Create quotation</button><button onClick={()=>setMsg('Create customer order will be built in a later module.')}>Create customer order</button><button onClick={()=>setMsg('Create invoice will be built in a later module.')}>Create invoice</button><button onClick={()=>archive(c.id)}>Archive</button><button onClick={()=>del(c.id)}>Delete</button></td></tr>)}</tbody></table></div>
    {open && <div className='fixed inset-0 z-50'><button className='absolute inset-0 bg-black/30' onClick={()=>setOpen(false)} /><aside className='absolute right-0 top-0 h-full w-full max-w-2xl overflow-y-auto bg-white p-5'><h3 className='text-lg font-semibold'>{editing?'Edit':'Add'} Customer</h3><div className='mt-4 grid gap-3 md:grid-cols-2'>{['contactName','companyName','phone','email','deliveryAddressLine1','deliveryAddressLine2','deliveryPostalCode','deliveryCountry','billingAddressLine1','billingAddressLine2','billingPostalCode','billingCountry'].map(k=><input key={k} className='border rounded px-3 py-2 text-sm' placeholder={k} value={form[k]||''} onChange={e=>setForm((f:any)=>({...f,[k]:e.target.value}))} />)}<select className='border rounded px-3 py-2 text-sm' value={form.customerType||'SCHOOL'} onChange={e=>setForm((f:any)=>({...f,customerType:e.target.value}))}>{CUSTOMER_TYPES.map(t=><option key={t}>{t}</option>)}</select><select className='border rounded px-3 py-2 text-sm' value={form.status||'LEAD'} onChange={e=>setForm((f:any)=>({...f,status:e.target.value}))}>{CUSTOMER_STATUSES.map(s=><option key={s}>{s}</option>)}</select><textarea className='border rounded px-3 py-2 text-sm md:col-span-2' placeholder='notes' value={form.notes||''} onChange={e=>setForm((f:any)=>({...f,notes:e.target.value}))} /><label className='text-sm md:col-span-2'><input type='checkbox' checked={form.billingSame??true} onChange={e=>setForm((f:any)=>({...f,billingSame:e.target.checked}))}/> Billing address same as delivery address</label><div className='md:col-span-2 grid grid-cols-2 gap-2'>{CUSTOMER_TAGS.map(tag=><label key={tag} className='text-xs'><input type='checkbox' checked={(form.tags||[]).includes(tag)} onChange={e=>setForm((f:any)=>({...f,tags:e.target.checked?[...(f.tags||[]),tag]:(f.tags||[]).filter((x:string)=>x!==tag)}))}/> {tag}</label>)}</div></div><div className='mt-4 flex justify-end gap-2'><button className='border rounded px-3 py-2' onClick={()=>setOpen(false)}>Cancel</button><button className='bg-slate-900 text-white rounded px-3 py-2' onClick={save}>Save</button></div></aside></div>}
  </section>;
}
