import { prisma } from '@/lib/prisma';
import Link from 'next/link';
import { StatusBadge } from '@/components/ui/StatusBadge';

export default async function CustomerDetail({ params }: { params: { id: string } }) {
  const customer = await prisma.customer.findUnique({ where: { id: params.id }, include: { customerNotes: true, attachments: true, followUps: true, activities: { orderBy: { createdAt: 'desc' } } } });
  if (!customer) return <div>Customer not found</div>;
  return <section className='space-y-4'><Link href='/customers' className='text-sm underline'>Back to customers</Link><div className='rounded border bg-white p-4'><h1 className='text-2xl font-semibold'>{customer.contactName}</h1><p>{customer.companyName || 'No organisation'}</p><div className='mt-2'><StatusBadge status={customer.status.replace('_',' ')} /></div><p className='mt-2 text-sm'>{customer.customerType} • {customer.phone} • {customer.email}</p><p className='mt-2 text-sm'>Tags: {customer.tags.join(', ') || '-'}</p></div>
  <div className='grid gap-4 xl:grid-cols-2'><div className='rounded border bg-white p-4'><h3 className='font-semibold'>Addresses</h3><p className='mt-2 text-sm'>Delivery: {customer.deliveryAddressLine1} {customer.deliveryAddressLine2 || ''}, {customer.deliveryPostalCode}, {customer.deliveryCountry}</p><p className='mt-2 text-sm'>Billing: {customer.billingAddressLine1 || '-'} {customer.billingAddressLine2 || ''}, {customer.billingPostalCode || '-'}, {customer.billingCountry || '-'}</p></div><div className='rounded border bg-white p-4'><h3 className='font-semibold'>Metrics (placeholder)</h3><p className='text-sm mt-2'>Total revenue: SGD 0.00</p><p className='text-sm'>Total gross profit: SGD 0.00</p><p className='text-sm'>Quotations: 0</p><p className='text-sm'>Confirmed customer orders: 0</p><p className='text-sm'>Outstanding invoice amount: SGD 0.00</p><p className='text-sm'>Average order value: SGD 0.00</p><p className='text-sm'>Last order date: -</p></div></div>
  <div className='rounded border bg-white p-4'><h3 className='font-semibold'>Customer images</h3>{customer.attachments.length===0?<p className='text-sm text-slate-600 mt-2'>No images uploaded.</p>:<ul>{customer.attachments.map(a=><li key={a.id}><a className='underline' href={a.fileUrl} target='_blank'>{a.fileName}</a> - {a.description || '-'}</li>)}</ul>}</div>
  <div className='rounded border bg-white p-4'><h3 className='font-semibold'>Main notes</h3><p className='mt-2 text-sm'>{customer.notes || 'No main notes.'}</p><h4 className='mt-4 font-medium'>Timestamped notes</h4><ul className='mt-2 text-sm'>{customer.customerNotes.map(n=><li key={n.id}>{new Date(n.createdAt).toLocaleString()} - {n.content}</li>)}</ul></div>
  <div className='rounded border bg-white p-4'><h3 className='font-semibold'>Follow-ups</h3><ul className='mt-2 text-sm'>{customer.followUps.map(f=><li key={f.id}>{f.title} ({f.type}) - {f.status} - due {new Date(f.dueDate).toLocaleDateString()}</li>)}</ul></div>
  <div className='rounded border bg-white p-4'><h3 className='font-semibold'>Activity log</h3><ul className='mt-2 text-sm'>{customer.activities.map(a=><li key={a.id}>{new Date(a.createdAt).toLocaleString()} - {a.description}</li>)}</ul></div>
  <div className='rounded border bg-white p-4'><h3 className='font-semibold'>Linked records placeholders</h3><p className='text-sm mt-2'>Quotations, Customer Orders, Invoices, Payment history will appear here in later modules.</p></div>
  </section>;
}
